In [2]:
import polars as pl
from ergochemics.standardize import standardize_smiles, hash_reaction
from functools import partial
from ergochemics.draw import draw_molecule

In [84]:
std_smi = partial(standardize_smiles, neutralization_method="simple", quiet=True)

In [85]:
name_smi = {}
with open("/home/stef/bottle/artifacts/4228703247252781668.txt", "r") as f:
    for line in f.readlines():
        split_line = line.strip().split("\t")
        if len(split_line) == 2:
            name, smi = split_line
            name_smi[name] = std_smi(smi)

In [86]:
beachheads = [
    "D-Xylose",
    "Protocatechuic acid",
    "Pyruvate",
    "Malonyl-CoA",
    "L-aspartate",
    "Citrate",
    "Geranyl diphosphate",
    "Geranylgeranyl diphosphate",
    "Farnesyl diphosphate",
    "L-glutamate",
]

potential_beachheads = [
    "Glycerol",
    "L-Tyrosine",
    "Prephenic acid",
    "Chorismate",
    "Acetolactate",
    "2-Ketoisovalerate",
    "Acetoacetyl-CoA",
    "Acetyl-CoA",
    "2-Ketobutyric acid",
    "Propionyl-CoA",
    "L-lysine",
    "Glutaric acid",
    "Succinyl-CoA",
    "L-Proline",
    "L-Arginine",
]

targets = [
    "cis,cis-Muconic acid",
    "3-Hydroxypropionic acid",
    "cis-Aconitate",
    "Cineole",
    "Bisabolene",
    "Kaurene"
]

In [87]:
missing_smiles = []
for group_name, group in zip(["beachheads", "potential_beachheads", "targets"], [beachheads, potential_beachheads, targets]):
    for name in group:
        missing_smiles.append(name) if name not in name_smi else None

In [88]:
missing_smiles

[]

In [89]:
with open("round_2.txt", "w") as f:
    for name in missing_smiles:
        f.write(f"{name}\n")

In [90]:
table = []
for name, smi in name_smi.items():
    table.append(
        [name, smi, name in beachheads, name in potential_beachheads, name in targets]
    )   
    
df = pl.DataFrame(
    table,
    schema=[
        ("name", pl.String),
        ("smiles", pl.String),
        ("beachhead", pl.Boolean),
        ("potential_beachhead", pl.Boolean),
        ("target", pl.Boolean),
    ]
)
df.head()

/tmp/ipykernel_175240/18072210.py:7: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  df = pl.DataFrame(

shape: (5, 5)
┌──────────────────────┬──────────────────────┬───────────┬─────────────────────┬────────┐
│ name                 ┆ smiles               ┆ beachhead ┆ potential_beachhead ┆ target │
│ ---                  ┆ ---                  ┆ ---       ┆ ---                 ┆ ---    │
│ str                  ┆ str                  ┆ bool      ┆ bool                ┆ bool   │
╞══════════════════════╪══════════════════════╪═══════════╪═════════════════════╪════════╡
│ Glucose              ┆ OCC1OC(O)C(O)C(O)C1O ┆ false     ┆ false               ┆ false  │
│ Pyruvate             ┆ CC(=O)C(=O)O         ┆ true      ┆ false               ┆ false  │
│ D-xylono-1,4-lactone ┆ O=C1OC(CO)C(O)C1O    ┆ false     ┆ false               ┆ false  │
│ 4-Hydroxyhexan-3-one ┆ CCC(=O)C(O)CC        ┆ false     ┆ false               ┆ false  │
│ Propanal             ┆ CCC=O                ┆ false     ┆ false               ┆ false  │
└──────────────────────┴──────────────────────┴───────────┴─────────────────────┴────────┘

In [91]:
df.write_csv(
    "/home/stef/bottle/artifacts/agile_biofoundry.tsv",
    separator="\t",
)

In [10]:
am = pl.read_parquet(
    "/home/stef/quest_data/bottle/data/interim/expansions/lin_test/am_rxns.parquet"
)
am.head()

shape: (5, 4)
┌──────────────────────────────┬──────────────────────────────┬─────────────────────────────┬──────┐
│ smarts                       ┆ am_smarts                    ┆ rules                       ┆ size │
│ ---                          ┆ ---                          ┆ ---                         ┆ ---  │
│ str                          ┆ str                          ┆ list[str]                   ┆ i32  │
╞══════════════════════════════╪══════════════════════════════╪═════════════════════════════╪══════╡
│ O.CC(C)(COP(=O)(O)OP(=O)(O)O ┆ [OH2:63].[CH3:1][C:2]([CH3:3 ┆ ["mechinferred_dt_04:1312", ┆ 7    │
│ CC…                          ┆ ])…                          ┆ "m…                         ┆      │
│ O=C(O)C(=O)CC(=O)C(=O)O.O=O> ┆ [O:1]=[C:2]([OH:3])[C:4](=[O ┆ ["mechinferred_dt_13:1892"] ┆ 7    │
│ >O…                          ┆ :5…                          ┆                             ┆      │
│ Nc1ncnc2c1ncn2C1OC(COP(=O)(O ┆ [NH2:1][c:2]1[n:3][cH:4][n:5 ┆ ["mechinferred_dt_13:3348"] ┆ 26   │
│ )O…                          ┆ ][…                          ┆                             ┆      │
│ O=C(O)C1CCC(CNC(O)C(=O)C(O)C ┆ [O:1]=[C:2]([OH:3])[CH:4]1[C ┆ ["mechinferred_dt_04:6720", ┆ 18   │
│ (O…                          ┆ H2…                          ┆ "m…                         ┆      │
│ COP(=O)(OCC1OC(n2cnc3c(N)ncn ┆ [CH3:1][O:39][P:37](=[O:38]) ┆ ["mechinferred_dt_04:410",  ┆ 7    │
│ c3…                          ┆ ([…                          ┆ "me…                        ┆      │
└──────────────────────────────┴──────────────────────────────┴─────────────────────────────┴──────┘

In [11]:
am = am.with_columns(
    pl.col("smarts").map_elements(hash_reaction, return_dtype=pl.String).alias("rid")
)
am.head()

shape: (5, 5)
┌──────────────────────┬──────────────────────┬──────────────────────┬──────┬──────────────────────┐
│ smarts               ┆ am_smarts            ┆ rules                ┆ size ┆ rid                  │
│ ---                  ┆ ---                  ┆ ---                  ┆ ---  ┆ ---                  │
│ str                  ┆ str                  ┆ list[str]            ┆ i32  ┆ str                  │
╞══════════════════════╪══════════════════════╪══════════════════════╪══════╪══════════════════════╡
│ O.CC(C)(COP(=O)(O)OP ┆ [OH2:63].[CH3:1][C:2 ┆ ["mechinferred_dt_04 ┆ 7    ┆ bf58984a60a19bd6f144 │
│ (=O)(O)OCC…          ┆ ]([CH3:3])…          ┆ :1312", "m…          ┆      ┆ 558c51ddd4…          │
│ O=C(O)C(=O)CC(=O)C(= ┆ [O:1]=[C:2]([OH:3])[ ┆ ["mechinferred_dt_13 ┆ 7    ┆ e78c6b441bae00c14562 │
│ O)O.O=O>>O…          ┆ C:4](=[O:5…          ┆ :1892"]              ┆      ┆ 0767621ab0…          │
│ Nc1ncnc2c1ncn2C1OC(C ┆ [NH2:1][c:2]1[n:3][c ┆ ["mechinferred_dt_13 ┆ 26   ┆ 022dd2e433c1d742fc9a │
│ OP(=O)(O)O…          ┆ H:4][n:5][…          ┆ :3348"]              ┆      ┆ d553f6ee5a…          │
│ O=C(O)C1CCC(CNC(O)C( ┆ [O:1]=[C:2]([OH:3])[ ┆ ["mechinferred_dt_04 ┆ 18   ┆ 2c89870c1cf039749ac0 │
│ =O)C(O)C(O…          ┆ CH:4]1[CH2…          ┆ :6720", "m…          ┆      ┆ b89b11baa3…          │
│ COP(=O)(OCC1OC(n2cnc ┆ [CH3:1][O:39][P:37]( ┆ ["mechinferred_dt_04 ┆ 7    ┆ fbdee7d3113c295a3b86 │
│ 3c(N)ncnc3…          ┆ =[O:38])([…          ┆ :410", "me…          ┆      ┆ 7a4fff8bf0…          │
└──────────────────────┴──────────────────────┴──────────────────────┴──────┴──────────────────────┘

In [12]:
rids_required = [
    '5582845919356f447668dd0ea4647fbddf01b7ac',
    '8c16137b4045f00069ba91d38a3b8b8ada3829c4',
    '9c2c777c0fea421a26efc26857522fd2ccce1555',
    '27450e93bf1eb2d982a541e9b34724d7623e5cd6',
    '646032df080e79e8522e14d05d85481075986e08',
    '62277981d883290bf5c0d4ed25855547d908a0b4',
    'e86048734a2f69f1257bd92b62ddb418a781fe98',
    'bd616dde067e2786bec3a4ea2c6e17d2d299dce4',
]

test_am = am.filter(pl.col("rid").is_in(rids_required))
print(len(test_am))

4

In [13]:
test_am

shape: (4, 5)
┌──────────────────────┬──────────────────────┬──────────────────────┬──────┬──────────────────────┐
│ smarts               ┆ am_smarts            ┆ rules                ┆ size ┆ rid                  │
│ ---                  ┆ ---                  ┆ ---                  ┆ ---  ┆ ---                  │
│ str                  ┆ str                  ┆ list[str]            ┆ i32  ┆ str                  │
╞══════════════════════╪══════════════════════╪══════════════════════╪══════╪══════════════════════╡
│ CC(O)(CC(=O)SCCNC(=O ┆ [CH3:1][C:2]([OH:3]) ┆ ["mechinferred_dt_13 ┆ 8    ┆ 8c16137b4045f00069ba │
│ )CCNC(=O)C…          ┆ ([CH2:4][C…          ┆ :2937", "m…          ┆      ┆ 91d38a3b8b…          │
│ CC(=O)SCCNC(=O)CCNC( ┆ [CH3:4][C:5](=[O:6]) ┆ ["mechinferred_dt_04 ┆ 13   ┆ 5582845919356f447668 │
│ =O)C(O)C(C…          ┆ [S:7][CH2:…          ┆ :3160", "m…          ┆      ┆ dd0ea4647f…          │
│ NC(CCC(=O)O)C(=O)O>> ┆ [NH2:1][CH:2]([CH2:3 ┆ ["mechinferred_dt_13 ┆ 9    ┆ 27450e93bf1eb2d982a5 │
│ CC(C(=O)O)…          ┆ ][CH2:4][C…          ┆ :5008"]              ┆      ┆ 41e9b34724…          │
│ CC(C(=O)O)C(N)C(=O)O ┆ [CH3:1][CH:2]([C:3]( ┆ ["mechinferred_dt_13 ┆ 6    ┆ 646032df080e79e8522e │
│ .CC(=O)SCC…          ┆ =[O:4])[OH…          ┆ :55"]                ┆      ┆ 14d05d8548…          │
└──────────────────────┴──────────────────────┴──────────────────────┴──────┴──────────────────────┘