In [7]:
import polars as pl
from ergochemics.standardize import standardize_smiles, hash_reaction
from functools import partial
from ergochemics.draw import draw_molecule

In [84]:
std_smi = partial(standardize_smiles, neutralization_method="simple", quiet=True)

In [85]:
name_smi = {}
with open("/home/stef/bottle/artifacts/4228703247252781668.txt", "r") as f:
    for line in f.readlines():
        split_line = line.strip().split("\t")
        if len(split_line) == 2:
            name, smi = split_line
            name_smi[name] = std_smi(smi)

In [86]:
beachheads = [
    "D-Xylose",
    "Protocatechuic acid",
    "Pyruvate",
    "Malonyl-CoA",
    "L-aspartate",
    "Citrate",
    "Geranyl diphosphate",
    "Geranylgeranyl diphosphate",
    "Farnesyl diphosphate",
    "L-glutamate",
]

potential_beachheads = [
    "Glycerol",
    "L-Tyrosine",
    "Prephenic acid",
    "Chorismate",
    "Acetolactate",
    "2-Ketoisovalerate",
    "Acetoacetyl-CoA",
    "Acetyl-CoA",
    "2-Ketobutyric acid",
    "Propionyl-CoA",
    "L-lysine",
    "Glutaric acid",
    "Succinyl-CoA",
    "L-Proline",
    "L-Arginine",
]

targets = [
    "cis,cis-Muconic acid",
    "3-Hydroxypropionic acid",
    "cis-Aconitate",
    "Cineole",
    "Bisabolene",
    "Kaurene"
]

In [87]:
missing_smiles = []
for group_name, group in zip(["beachheads", "potential_beachheads", "targets"], [beachheads, potential_beachheads, targets]):
    for name in group:
        missing_smiles.append(name) if name not in name_smi else None

In [88]:
missing_smiles

[]

In [89]:
with open("round_2.txt", "w") as f:
    for name in missing_smiles:
        f.write(f"{name}\n")

In [90]:
table = []
for name, smi in name_smi.items():
    table.append(
        [name, smi, name in beachheads, name in potential_beachheads, name in targets]
    )   
    
df = pl.DataFrame(
    table,
    schema=[
        ("name", pl.String),
        ("smiles", pl.String),
        ("beachhead", pl.Boolean),
        ("potential_beachhead", pl.Boolean),
        ("target", pl.Boolean),
    ]
)
df.head()

/tmp/ipykernel_175240/18072210.py:7: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  df = pl.DataFrame(

shape: (5, 5)
┌──────────────────────┬──────────────────────┬───────────┬─────────────────────┬────────┐
│ name                 ┆ smiles               ┆ beachhead ┆ potential_beachhead ┆ target │
│ ---                  ┆ ---                  ┆ ---       ┆ ---                 ┆ ---    │
│ str                  ┆ str                  ┆ bool      ┆ bool                ┆ bool   │
╞══════════════════════╪══════════════════════╪═══════════╪═════════════════════╪════════╡
│ Glucose              ┆ OCC1OC(O)C(O)C(O)C1O ┆ false     ┆ false               ┆ false  │
│ Pyruvate             ┆ CC(=O)C(=O)O         ┆ true      ┆ false               ┆ false  │
│ D-xylono-1,4-lactone ┆ O=C1OC(CO)C(O)C1O    ┆ false     ┆ false               ┆ false  │
│ 4-Hydroxyhexan-3-one ┆ CCC(=O)C(O)CC        ┆ false     ┆ false               ┆ false  │
│ Propanal             ┆ CCC=O                ┆ false     ┆ false               ┆ false  │
└──────────────────────┴──────────────────────┴───────────┴─────────────────────┴────────┘

In [91]:
df.write_csv(
    "/home/stef/bottle/artifacts/agile_biofoundry.tsv",
    separator="\t",
)

In [16]:
am = pl.read_parquet(
    "/home/stef/quest_data/bottle/data/interim/expansions/lin_test/am_rxns.parquet"
)
am.head()

shape: (5, 5)
┌──────────────────────┬──────────────────────┬──────────────────────┬──────┬──────────────────────┐
│ smarts               ┆ am_smarts            ┆ rules                ┆ size ┆ rid                  │
│ ---                  ┆ ---                  ┆ ---                  ┆ ---  ┆ ---                  │
│ str                  ┆ str                  ┆ list[str]            ┆ i32  ┆ str                  │
╞══════════════════════╪══════════════════════╪══════════════════════╪══════╪══════════════════════╡
│ NC(CCC(=O)O)C(=O)O>> ┆ [NH2:1][CH:2]([CH2:3 ┆ ["mechinferred_dt_13 ┆ 9    ┆ 27450e93bf1eb2d982a5 │
│ CC(C(=O)O)…          ┆ ][CH2:4][C…          ┆ :5008"]              ┆      ┆ 41e9b34724…          │
│ CC(CC(=O)SCCNC(=O)CC ┆ [CH3:3][CH:2]([CH2:1 ┆ ["mechinferred_dt_04 ┆ 5    ┆ e86048734a2f69f1257b │
│ NC(=O)C(O)…          ┆ ][C:7](=[O…          ┆ :3939"]              ┆      ┆ d92b62ddb4…          │
│ NC(=O)C1=CN(C2OC(COP ┆ [NH2:58][C:59](=[O:6 ┆ ["mechinferred_dt_04 ┆ 15   ┆ 62277981d883290bf5c0 │
│ (=O)(O)OP(…          ┆ 0])[C:61]1…          ┆ :6695"]              ┆      ┆ d4ed258555…          │
│ CC(O)(CC(=O)SCCNC(=O ┆ [CH3:1][C:2]([OH:3]) ┆ ["mechinferred_dt_13 ┆ 8    ┆ 8c16137b4045f00069ba │
│ )CCNC(=O)C…          ┆ ([CH2:4][C…          ┆ :2441", "m…          ┆      ┆ 91d38a3b8b…          │
│ NC(=O)C1=CN(C2OC(COP ┆ [NH2:105][C:106](=[O ┆ ["mechinferred_dt_04 ┆ 26   ┆ bd616dde067e2786bec3 │
│ (=O)(O)OP(…          ┆ :107])[C:1…          ┆ :4272", "m…          ┆      ┆ a4ea2c6e17…          │
└──────────────────────┴──────────────────────┴──────────────────────┴──────┴──────────────────────┘

In [17]:
am = am.with_columns(
    pl.col("smarts").map_elements(hash_reaction, return_dtype=pl.String).alias("rid")
)
am.head()

shape: (5, 5)
┌──────────────────────┬──────────────────────┬──────────────────────┬──────┬──────────────────────┐
│ smarts               ┆ am_smarts            ┆ rules                ┆ size ┆ rid                  │
│ ---                  ┆ ---                  ┆ ---                  ┆ ---  ┆ ---                  │
│ str                  ┆ str                  ┆ list[str]            ┆ i32  ┆ str                  │
╞══════════════════════╪══════════════════════╪══════════════════════╪══════╪══════════════════════╡
│ NC(CCC(=O)O)C(=O)O>> ┆ [NH2:1][CH:2]([CH2:3 ┆ ["mechinferred_dt_13 ┆ 9    ┆ 27450e93bf1eb2d982a5 │
│ CC(C(=O)O)…          ┆ ][CH2:4][C…          ┆ :5008"]              ┆      ┆ 41e9b34724…          │
│ CC(CC(=O)SCCNC(=O)CC ┆ [CH3:3][CH:2]([CH2:1 ┆ ["mechinferred_dt_04 ┆ 5    ┆ e86048734a2f69f1257b │
│ NC(=O)C(O)…          ┆ ][C:7](=[O…          ┆ :3939"]              ┆      ┆ d92b62ddb4…          │
│ NC(=O)C1=CN(C2OC(COP ┆ [NH2:58][C:59](=[O:6 ┆ ["mechinferred_dt_04 ┆ 15   ┆ 62277981d883290bf5c0 │
│ (=O)(O)OP(…          ┆ 0])[C:61]1…          ┆ :6695"]              ┆      ┆ d4ed258555…          │
│ CC(O)(CC(=O)SCCNC(=O ┆ [CH3:1][C:2]([OH:3]) ┆ ["mechinferred_dt_13 ┆ 8    ┆ 8c16137b4045f00069ba │
│ )CCNC(=O)C…          ┆ ([CH2:4][C…          ┆ :2441", "m…          ┆      ┆ 91d38a3b8b…          │
│ NC(=O)C1=CN(C2OC(COP ┆ [NH2:105][C:106](=[O ┆ ["mechinferred_dt_04 ┆ 26   ┆ bd616dde067e2786bec3 │
│ (=O)(O)OP(…          ┆ :107])[C:1…          ┆ :4272", "m…          ┆      ┆ a4ea2c6e17…          │
└──────────────────────┴──────────────────────┴──────────────────────┴──────┴──────────────────────┘

In [18]:
rids_required = [
    '5582845919356f447668dd0ea4647fbddf01b7ac',
    '8c16137b4045f00069ba91d38a3b8b8ada3829c4',
    '9c2c777c0fea421a26efc26857522fd2ccce1555',
    '27450e93bf1eb2d982a541e9b34724d7623e5cd6',
    '646032df080e79e8522e14d05d85481075986e08',
    '62277981d883290bf5c0d4ed25855547d908a0b4',
    'e86048734a2f69f1257bd92b62ddb418a781fe98',
    'bd616dde067e2786bec3a4ea2c6e17d2d299dce4',
]

test_am = am.filter(pl.col("rid").is_in(rids_required))
print(len(test_am))

8

In [19]:
test_am

shape: (8, 5)
┌──────────────────────┬──────────────────────┬──────────────────────┬──────┬──────────────────────┐
│ smarts               ┆ am_smarts            ┆ rules                ┆ size ┆ rid                  │
│ ---                  ┆ ---                  ┆ ---                  ┆ ---  ┆ ---                  │
│ str                  ┆ str                  ┆ list[str]            ┆ i32  ┆ str                  │
╞══════════════════════╪══════════════════════╪══════════════════════╪══════╪══════════════════════╡
│ NC(CCC(=O)O)C(=O)O>> ┆ [NH2:1][CH:2]([CH2:3 ┆ ["mechinferred_dt_13 ┆ 9    ┆ 27450e93bf1eb2d982a5 │
│ CC(C(=O)O)…          ┆ ][CH2:4][C…          ┆ :5008"]              ┆      ┆ 41e9b34724…          │
│ CC(CC(=O)SCCNC(=O)CC ┆ [CH3:3][CH:2]([CH2:1 ┆ ["mechinferred_dt_04 ┆ 5    ┆ e86048734a2f69f1257b │
│ NC(=O)C(O)…          ┆ ][C:7](=[O…          ┆ :3939"]              ┆      ┆ d92b62ddb4…          │
│ NC(=O)C1=CN(C2OC(COP ┆ [NH2:58][C:59](=[O:6 ┆ ["mechinferred_dt_04 ┆ 15   ┆ 62277981d883290bf5c0 │
│ (=O)(O)OP(…          ┆ 0])[C:61]1…          ┆ :6695"]              ┆      ┆ d4ed258555…          │
│ CC(O)(CC(=O)SCCNC(=O ┆ [CH3:1][C:2]([OH:3]) ┆ ["mechinferred_dt_13 ┆ 8    ┆ 8c16137b4045f00069ba │
│ )CCNC(=O)C…          ┆ ([CH2:4][C…          ┆ :2441", "m…          ┆      ┆ 91d38a3b8b…          │
│ NC(=O)C1=CN(C2OC(COP ┆ [NH2:105][C:106](=[O ┆ ["mechinferred_dt_04 ┆ 26   ┆ bd616dde067e2786bec3 │
│ (=O)(O)OP(…          ┆ :107])[C:1…          ┆ :4272", "m…          ┆      ┆ a4ea2c6e17…          │
│ CC(C(=O)O)C(N)C(=O)O ┆ [CH3:1][CH:2]([C:3]( ┆ ["mechinferred_dt_13 ┆ 6    ┆ 646032df080e79e8522e │
│ .CC(=O)SCC…          ┆ =[O:4])[OH…          ┆ :55"]                ┆      ┆ 14d05d8548…          │
│ CC(=O)SCCNC(=O)CCNC( ┆ [CH3:4][C:5](=[O:6]) ┆ ["mechinferred_dt_04 ┆ 13   ┆ 5582845919356f447668 │
│ =O)C(O)C(C…          ┆ [S:7][CH2:…          ┆ :3160", "m…          ┆      ┆ dd0ea4647f…          │
│ CC(=CC(=O)SCCNC(=O)C ┆ [CH3:1][C:2](=[CH:3] ┆ ["mechinferred_dt_04 ┆ 12   ┆ 9c2c777c0fea421a26ef │
│ CNC(=O)C(O…          ┆ [C:4](=[O:…          ┆ :3778"]              ┆      ┆ c26857522f…          │
└──────────────────────┴──────────────────────┴──────────────────────┴──────┴──────────────────────┘

In [20]:
test_am.write_parquet("/home/stef/quest_data/bottle/data/interim/expansions/lin_test/am_rxns.parquet")

In [1]:
from minedatabase.pickaxe import Pickaxe

In [2]:
pk = Pickaxe()
pk.load_pickled_pickaxe(
    "/home/stef/quest_data/bottle/results/raw_expansions/2_steps_bottle_targets_25_to_None_rules_mechinferred_dt_01_rules_w_coreactants_co_metacyc_coreactants_sampled_False_pruned_False_aplusb_False.pk"
)

----------------------------------------
Intializing pickaxe object

Done intializing pickaxe object
----------------------------------------

Loading /home/stef/quest_data/bottle/results/raw_expansions/2_steps_bottle_targets_25_to_None_rules_mechinferred_dt_01_rules_w_coreactants_co_metacyc_coreactants_sampled_False_pruned_False_aplusb_False.pk pickled data.
Loaded 904 compounds
Loaded 1452 reactions
Loaded 17661 operators
Loaded 45 coreactants
Loaded 2 generation
Took 10.144115686416626

[09:49:18] WARNING: not removing hydrogen atom without neighbors

In [5]:
pk.targets

{}

In [10]:
cpds = pl.read_parquet(
    "/home/stef/quest_data/bottle/data/interim/expansions/2_steps_ccm_aa_to_None_rules_mechinferred_dt_13_rules_w_coreactants_co_metacyc_coreactants_sampled_False_pruned_False_aplusb_True/compounds.parquet"
)
cpds

shape: (70, 4)
┌─────────────────────────────────┬─────────────────────┬────────┬───────────────┐
│ id                              ┆ smiles              ┆ type   ┆ name          │
│ ---                             ┆ ---                 ┆ ---    ┆ ---           │
│ str                             ┆ str                 ┆ enum   ┆ str           │
╞═════════════════════════════════╪═════════════════════╪════════╪═══════════════╡
│ fae11404b12230ded37cfd2511bf3d… ┆ O=C(O)CCC(=O)O      ┆ source ┆ succinate     │
│ 55e7ca03fb953e8974749691680048… ┆ O=C(O)C=CC(=O)O     ┆ source ┆ fumarate      │
│ 77d21e11cc906a4c9614c97db30147… ┆ O=C(O)CC(O)C(=O)O   ┆ source ┆ malate        │
│ 20e696beb1325772afccb7eb1d2c18… ┆ O=C(O)CC(=O)C(=O)O  ┆ source ┆ oxaloacetate  │
│ 6cf6db1d70f43061de31deeb417214… ┆ O=C(O)CCC(=O)C(=O)O ┆ source ┆ ketoglutarate │
│ …                               ┆ …                   ┆ …      ┆ …             │
│ 1aa818910461f5961959eb05dd06b8… ┆ O=O                 ┆ helper ┆ O2            │
│ cd67f644cdcbc3175749023bdcb6d2… ┆ O=P(O)(O)O          ┆ helper ┆ Pi            │
│ 3496c01ecd09448b8e3228ded69813… ┆ O=S(=O)(O)O         ┆ helper ┆ SULFATE       │
│ 7101b465adaa44192c904953310525… ┆ O=S(O)O             ┆ helper ┆ SULFITE       │
│ 08a914cde05039694ef0194d9ee79f… ┆ O                   ┆ helper ┆ WATER         │
└─────────────────────────────────┴─────────────────────┴────────┴───────────────┘