In [13]:
from src.post_processing import PathWrangler
import polars as pl
from pathlib import Path
from collections import defaultdict
from ergochemics.draw import draw_reaction, draw_molecule
from ergochemics.mapping import get_reaction_center
from ergochemics.similarity import MolFeaturizer, ReactionFingerprinter
from rdkit import Chem
from IPython.display import display, SVG
import numpy as np
from hydra import initialize, compose

In [14]:
# study = "/home/stef/quest_data/bottle/data/processed/260327_target_3hpa"
study = "/home/stef/quest_data/bottle/data/processed/260410_target_3hpa"
# study = "/projects/b1039/spn1560/bottle/data/processed/260327_target_3hpa"
# study = "/home/stef/quest_data/bottle/data/processed/260324_2_step_bi_akg_to_hopa"
known = "/home/stef/bottle/artifacts/known"
# out_dir = "/home/stef/bottle/artifacts/coa_mutase_paths"

Direct look at parquet files

In [15]:
with initialize(config_path="../conf/filepaths", version_base=None):
    filepaths = compose(config_name="filepaths")

In [16]:
cpds = pl.read_parquet(
    Path(study)  / "compounds.parquet"
)
cpds.head()

shape: (5, 4)
┌──────────────────────────────┬─────────────────────────────┬────────┬────────────────────────────┐
│ id                           ┆ smiles                      ┆ type   ┆ name                       │
│ ---                          ┆ ---                         ┆ ---    ┆ ---                        │
│ str                          ┆ str                         ┆ enum   ┆ str                        │
╞══════════════════════════════╪═════════════════════════════╪════════╪════════════════════════════╡
│ 07e48b419b37606b338ba3e838a8 ┆ Nc1ncnc2c1ncn2C1OC(COP(=O)( ┆ helper ┆ PYROPHOSPHATE_DONOR_CoF    │
│ e5…                          ┆ O)O…                        ┆        ┆                            │
│ 4ea34a41c2091b9cd31211993490 ┆ Nc1ncnc2c1ncn2C1OC(COP(=O)( ┆ helper ┆ PYROPHOSPHATE_ACCEPTOR_CoF │
│ 9d…                          ┆ O)O…                        ┆        ┆                            │
│ c1a94434194999200be197465c01 ┆ Cc1cc2nc3c(=O)[nH]c(=O)nc-3 ┆ helper ┆ FAD_CoF                    │
│ c3…                          ┆ n(C…                        ┆        ┆                            │
│ 37225a49e3ed17e65590fb5ed4d5 ┆ Cc1cc2c(cc1C)N(CC(O)C(O)C(O ┆ helper ┆ FADH2_CoF                  │
│ 36…                          ┆ )CO…                        ┆        ┆                            │
│ d149421ac53cc62325e84c168821 ┆ Nc1ncnc2c1ncn2C1OC(COP(=O)( ┆ helper ┆ PHOSPHATE_ACCEPTOR_CoF     │
│ 0e…                          ┆ O)O…                        ┆        ┆                            │
└──────────────────────────────┴─────────────────────────────┴────────┴────────────────────────────┘

In [17]:
paths = pl.read_parquet(
    Path(study) / "paths.parquet"
)
paths.head()

shape: (5, 5)
┌────────────────────────┬────────────────────────┬───────────────────────┬───────────┬────────────┐
│ path_id                ┆ rxn_id                 ┆ main_pdt_id           ┆ rxn_type  ┆ generation │
│ ---                    ┆ ---                    ┆ ---                   ┆ ---       ┆ ---        │
│ str                    ┆ str                    ┆ str                   ┆ enum      ┆ i32        │
╞════════════════════════╪════════════════════════╪═══════════════════════╪═══════════╪════════════╡
│ 0bc7301a6d8122e4ae16c4 ┆ 3238d364a7911ad3440c41 ┆ cd431e4c6b05454079164 ┆ predicted ┆ 1          │
│ cfe5eb63…              ┆ c05c944a…              ┆ 7925df16a…            ┆           ┆            │
│ 0ccd84b14206a2bec2dbdf ┆ efb1c1d2bd82a3e0bb262e ┆ 692a548c92224b659ae0c ┆ predicted ┆ 1          │
│ 83ee4e90…              ┆ 80001631…              ┆ 86b41bc9c…            ┆           ┆            │
│ cf7dff1b59c7b6e8099361 ┆ f4028197d2316361e51352 ┆ 44a245a4a8752c17f6ab3 ┆ predicted ┆ 0          │
│ 663166aa…              ┆ 7282ccca…              ┆ 175f1aed4…            ┆           ┆            │
│ f9cc32cb062e5fc84f84a6 ┆ e00d2fd6f101dd3d9ac4cd ┆ 7adf4b7cf3272a4091055 ┆ predicted ┆ 2          │
│ d0a68e68…              ┆ a139cf0c…              ┆ af7ffa13e…            ┆           ┆            │
│ 860938b6f1f9e3d6de05bc ┆ 469d673e0020a199723ebd ┆ 6569ea8ebe9fdd8627adb ┆ predicted ┆ 4          │
│ cc90bb49…              ┆ def56551…              ┆ 76f7d942d…            ┆           ┆            │
└────────────────────────┴────────────────────────┴───────────────────────┴───────────┴────────────┘

In [18]:
path_stats = pl.read_parquet(
    Path(study) / "path_stats.parquet"
)
path_stats.head()

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ starters  ┆ targets   ┆ dg_opt    ┆ … ┆ mean_mean ┆ min_max_r ┆ min_mean_ ┆ feasibil │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ _rxn_sim  ┆ xn_sim    ┆ rxn_sim   ┆ ity_frac │
│ str       ┆ list[str] ┆ list[str] ┆ list[f32] ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆ f32       ┆ f32       ┆ f32       ┆ f32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 5e1957b85 ┆ ["serine" ┆ ["3hpa"]  ┆ [-1724.07 ┆ … ┆ 0.140728  ┆ 0.285714  ┆ 0.071105  ┆ 0.4      │
│ a15837c20 ┆ ]         ┆           ┆ 8491, 184 ┆   ┆           ┆           ┆           ┆          │
│ 463a3b3cd ┆           ┆           ┆ 5.854736, ┆   ┆           ┆           ┆           ┆          │
│ 150…      ┆           ┆           ┆ … …       ┆   ┆           ┆           ┆           ┆          │
│ 40c09c78c ┆ ["serine" ┆ ["3hpa"]  ┆ [-1714.96 ┆ … ┆ 0.222681  ┆ 0.163043  ┆ 0.05259   ┆ 0.4      │
│ 51f9d6282 ┆ ]         ┆           ┆ 9727,     ┆   ┆           ┆           ┆           ┆          │
│ 18d678aa1 ┆           ┆           ┆ -4.07868, ┆   ┆           ┆           ┆           ┆          │
│ 33a…      ┆           ┆           ┆ … -93…    ┆   ┆           ┆           ┆           ┆          │
│ c23194575 ┆ ["serine" ┆ ["3hpa"]  ┆ [-1040.78 ┆ … ┆ 0.086288  ┆ 0.167019  ┆ 0.038517  ┆ 0.4      │
│ ab132eec4 ┆ ]         ┆           ┆ 3813, -18 ┆   ┆           ┆           ┆           ┆          │
│ 83fc20b40 ┆           ┆           ┆ .191639,  ┆   ┆           ┆           ┆           ┆          │
│ 5de…      ┆           ┆           ┆ … 1…      ┆   ┆           ┆           ┆           ┆          │
│ 9a2aab407 ┆ ["succina ┆ ["3hpa"]  ┆ [-22.7197 ┆ … ┆ 0.368262  ┆ 0.111732  ┆ 0.094393  ┆ 0.6      │
│ e7b2d4277 ┆ te"]      ┆           ┆ 17, -23.6 ┆   ┆           ┆           ┆           ┆          │
│ 6817af80f ┆           ┆           ┆ 3415, …   ┆   ┆           ┆           ┆           ┆          │
│ 697…      ┆           ┆           ┆ -29.…     ┆   ┆           ┆           ┆           ┆          │
│ 1b7f047a6 ┆ ["ketoglu ┆ ["3hpa"]  ┆ [-7.05890 ┆ … ┆ 0.533775  ┆ 0.168831  ┆ 0.060807  ┆ 0.6      │
│ 3f43bbd19 ┆ tarate"]  ┆           ┆ 8, -7.058 ┆   ┆           ┆           ┆           ┆          │
│ e850a7fda ┆           ┆           ┆ 908, …    ┆   ┆           ┆           ┆           ┆          │
│ e38…      ┆           ┆           ┆ -10.1…    ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [19]:
print(paths.shape)
print(paths.unique().shape)
print(path_stats.shape)
print(path_stats.unique().shape)

(115261, 5)
(115261, 5)
(23400, 13)
(23400, 13)

In [20]:
pred_rxns = pl.read_parquet(
    Path(study) / "predicted_reactions.parquet"
)
print(pred_rxns.shape)
pred_rxns.head()

(7128, 9)

shape: (5, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ id        ┆ smarts    ┆ am_smarts ┆ dxgb_labe ┆ … ┆ analogue_ ┆ rules     ┆ templates ┆ rule_set │
│ ---       ┆ ---       ┆ ---       ┆ l         ┆   ┆ ids       ┆ ---       ┆ ---       ┆ s        │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ list[str] ┆ list[str] ┆ ---      │
│           ┆           ┆           ┆ i32       ┆   ┆ list[str] ┆           ┆           ┆ list[str │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ b01ec78f2 ┆ CCCO.O=C= ┆ [CH3:4][C ┆ 0         ┆ … ┆ ["8407819 ┆ ["499_0_r ┆ ["[C&D1&v ┆ ["mechin │
│ d79e43d56 ┆ O>>O=C(O) ┆ H2:5][CH2 ┆           ┆   ┆ 44e689e93 ┆ eversed"] ┆ 4&H3&+0&! ┆ ferred_d │
│ 933b4ce30 ┆ CCCO      ┆ :6][OH:7] ┆           ┆   ┆ 343dc2a06 ┆           ┆ R&z0:1].[ ┆ t_224_ru │
│ 2ff…      ┆           ┆ .[O…      ┆           ┆   ┆ 8ba…      ┆           ┆ O&D…      ┆ les_w_…  │
│ 5d05fb0be ┆ O=C(O)CCC ┆ [O:1]=[C: ┆ 1         ┆ … ┆ ["f843c12 ┆ ["143_1_0 ┆ ["[C&D3&v ┆ ["mechin │
│ 54ef57ed4 ┆ (=O)O.NC( ┆ 2]([OH:3] ┆           ┆   ┆ be8a52cc2 ┆ _0",      ┆ 4&H0&+0&! ┆ ferred_d │
│ 4932ac166 ┆ COP(=O)(O ┆ )[CH2:4][ ┆           ┆   ┆ 9ff38de4e ┆ "143_1",  ┆ R&z2:1](= ┆ t_956_ru │
│ 0b5…      ┆ )OP…      ┆ CH2…      ┆           ┆   ┆ 5de…      ┆ "143_1_…  ┆ [O&…      ┆ les_w_…  │
│ ec015573a ┆ O=C(O)CC( ┆ [O:1]=[C: ┆ 0         ┆ … ┆ ["95c3774 ┆ ["434_2"] ┆ ["[C&D2&v ┆ ["mechin │
│ 8794d1fcc ┆ =O)C(=O)O ┆ 2]([OH:3] ┆           ┆   ┆ 7aef287e1 ┆           ┆ 4&H2&+0&! ┆ ferred_d │
│ d20475501 ┆ .O=C=O.CC ┆ )[CH2:4][ ┆           ┆   ┆ 800c13465 ┆           ┆ R&z0:1]-[ ┆ t_956_ru │
│ 94c…      ┆ (C)…      ┆ C:5…      ┆           ┆   ┆ df0…      ┆           ┆ C&D…      ┆ les_w_…  │
│ 4c27c84e8 ┆ O=C(O)CCC ┆ [O:1]=[C: ┆ 1         ┆ … ┆ ["73a3231 ┆ ["47_3"]  ┆ ["[C&D3&v ┆ ["mechin │
│ e81f88121 ┆ (=O)OC(=O ┆ 2]([OH:3] ┆           ┆   ┆ dbf03c7a1 ┆           ┆ 4&H0&+0&! ┆ ferred_d │
│ 448a827bc ┆ )CCC(=O)O ┆ )[CH2:4][ ┆           ┆   ┆ 349c4ef53 ┆           ┆ R&z2:1](= ┆ t_956_ru │
│ 954…      ┆ .CC…      ┆ CH2…      ┆           ┆   ┆ 11e…      ┆           ┆ [O&…      ┆ les_w_…  │
│ b9ee27385 ┆ CC(C)(COP ┆ [CH3:26][ ┆ 1         ┆ … ┆ ["b4c25c2 ┆ ["1964_0_ ┆ ["[C&D3&v ┆ ["mechin │
│ 71dd49439 ┆ (=O)(O)OP ┆ C:25]([CH ┆           ┆   ┆ 88c30a8a0 ┆ reversed" ┆ 4&H1&+0&! ┆ ferred_d │
│ 2e7ea60ac ┆ (=O)(O)OC ┆ 3:27])([C ┆           ┆   ┆ c671f4f17 ┆ ]         ┆ R&z0:2]-[ ┆ t_224_ru │
│ c8b…      ┆ C1O…      ┆ H2:…      ┆           ┆   ┆ 129…      ┆           ┆ C&D…      ┆ les_w_…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [21]:
path_fb = pl.read_parquet(
    Path(study) / "path_feedback.parquet"
)
path_fb.head()

shape: (5, 5)
┌──────────┬─────────────────────────────────┬──────────┬────────────┬─────────────────┐
│ username ┆ id                              ┆ feedback ┆ date       ┆ time            │
│ ---      ┆ ---                             ┆ ---      ┆ ---        ┆ ---             │
│ str      ┆ str                             ┆ i32      ┆ date       ┆ time            │
╞══════════╪═════════════════════════════════╪══════════╪════════════╪═════════════════╡
│ Stefan   ┆ 679ce8c6e93c5c6e2f1d54772b57ee… ┆ 0        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│ Stefan   ┆ 0b7bb08c699db5934fb346b2b62807… ┆ 0        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│ Stefan   ┆ dfad596a72a8de6dc5321e895bc07f… ┆ 0        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│ Stefan   ┆ 787c56aee7410d3a28b4b7b22a5536… ┆ 0        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│ Stefan   ┆ 2f65915a529f9a86773e687909be2f… ┆ 1        ┆ 2026-04-17 ┆ 10:51:12.290072 │
└──────────┴─────────────────────────────────┴──────────┴────────────┴─────────────────┘

In [22]:
path_fb.shape

(44, 5)

In [23]:
rxn_fb = pl.read_parquet(
    Path(study) / "reaction_feedback.parquet"
)
rxn_fb.head()

shape: (5, 5)
┌──────────┬─────────────────────────────────┬──────────┬────────────┬─────────────────┐
│ username ┆ id                              ┆ feedback ┆ date       ┆ time            │
│ ---      ┆ ---                             ┆ ---      ┆ ---        ┆ ---             │
│ str      ┆ str                             ┆ i32      ┆ date       ┆ time            │
╞══════════╪═════════════════════════════════╪══════════╪════════════╪═════════════════╡
│ Stefan   ┆ 5959dace01dac3a519f9d50bb3af57… ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│ Stefan   ┆ fb4e2a8027e11dbec27fe6ca29a6bc… ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│ Stefan   ┆ dd322af258382cbc5680502046c37b… ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│ Stefan   ┆ 9038f7a31b67d543ce064375f4050b… ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│ Stefan   ┆ cecd6de9246a45d052a60c0829fe77… ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
└──────────┴─────────────────────────────────┴──────────┴────────────┴─────────────────┘

In [26]:
path_fb_update = path_fb.with_columns(
    pl.col("username").map_elements(lambda x: "stefanpate94@gmail.com" if x == "Stefan" else x).alias("username")
)
path_fb_update.head()

shape: (5, 5)
┌────────────────────────┬───────────────────────────────┬──────────┬────────────┬─────────────────┐
│ username               ┆ id                            ┆ feedback ┆ date       ┆ time            │
│ ---                    ┆ ---                           ┆ ---      ┆ ---        ┆ ---             │
│ str                    ┆ str                           ┆ i32      ┆ date       ┆ time            │
╞════════════════════════╪═══════════════════════════════╪══════════╪════════════╪═════════════════╡
│ stefanpate94@gmail.com ┆ 679ce8c6e93c5c6e2f1d54772b57e ┆ 0        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│                        ┆ e…                            ┆          ┆            ┆                 │
│ stefanpate94@gmail.com ┆ 0b7bb08c699db5934fb346b2b6280 ┆ 0        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│                        ┆ 7…                            ┆          ┆            ┆                 │
│ stefanpate94@gmail.com ┆ dfad596a72a8de6dc5321e895bc07 ┆ 0        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│                        ┆ f…                            ┆          ┆            ┆                 │
│ stefanpate94@gmail.com ┆ 787c56aee7410d3a28b4b7b22a553 ┆ 0        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│                        ┆ 6…                            ┆          ┆            ┆                 │
│ stefanpate94@gmail.com ┆ 2f65915a529f9a86773e687909be2 ┆ 1        ┆ 2026-04-17 ┆ 10:51:12.290072 │
│                        ┆ f…                            ┆          ┆            ┆                 │
└────────────────────────┴───────────────────────────────┴──────────┴────────────┴─────────────────┘

In [27]:
rxn_fb_update = rxn_fb.with_columns(
    pl.col("username").map_elements(lambda x: "stefanpate94@gmail.com" if x == "Stefan" else x).alias("username")
)
rxn_fb_update.head()

shape: (5, 5)
┌────────────────────────┬───────────────────────────────┬──────────┬────────────┬─────────────────┐
│ username               ┆ id                            ┆ feedback ┆ date       ┆ time            │
│ ---                    ┆ ---                           ┆ ---      ┆ ---        ┆ ---             │
│ str                    ┆ str                           ┆ i32      ┆ date       ┆ time            │
╞════════════════════════╪═══════════════════════════════╪══════════╪════════════╪═════════════════╡
│ stefanpate94@gmail.com ┆ 5959dace01dac3a519f9d50bb3af5 ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│                        ┆ 7…                            ┆          ┆            ┆                 │
│ stefanpate94@gmail.com ┆ fb4e2a8027e11dbec27fe6ca29a6b ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│                        ┆ c…                            ┆          ┆            ┆                 │
│ stefanpate94@gmail.com ┆ dd322af258382cbc5680502046c37 ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│                        ┆ b…                            ┆          ┆            ┆                 │
│ stefanpate94@gmail.com ┆ 9038f7a31b67d543ce064375f4050 ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│                        ┆ b…                            ┆          ┆            ┆                 │
│ stefanpate94@gmail.com ┆ cecd6de9246a45d052a60c0829fe7 ┆ 0        ┆ 2026-04-16 ┆ 16:15:55.825690 │
│                        ┆ 7…                            ┆          ┆            ┆                 │
└────────────────────────┴───────────────────────────────┴──────────┴────────────┴─────────────────┘